chore: change to meson build -> meson setup build
Signed-off-by: Naoki Aoyama <9667078+naa0yama@users.noreply.github.com>

diff --git a/scripts/test_jlse b/scripts/test_jlse
--- a/scripts/test_jlse
+++ b/scripts/test_jlse
@@ -50,40 +50,47 @@ if [[ ! -f "${INPUT}" ]]; then
 	cp output/scene_06min/jtv_scene_06min.ts /source
 fi
 
-	if ! jlse --input "${INPUT}"; then
-		logger "## jlse failed with exit code $?. Stopping execution." red
-		exit 1
-	fi
-	src_duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "${INPUT}")
-	dst_duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "/join_logo_scp_trial/result/$(basename ${INPUT} .ts)/in_cutcm_logo.avs")
-	set +x
-	logger "## ============================================================================="
-	logger "## Report test_jlse."
-	logger "## - source:       ${INPUT}"
-	logger "##    - duration:  ${src_duration%.*}"
-	logger "## - destnation:   ${INPUT%.ts}.mp4"
-	logger "##    - duration:  ${dst_duration%.*}"
-	logger "## - versions:"
-	logger "$(jq -r '
-			{
-				"ffmpeg-jlstsl",
-				"liblsmash",
-				"liblsmash-url",
-				"liblsmashsource",
-				"liblsmashsource-url",
-				"libobuparse"
-			} as $data | ($data | keys | map(length) | max) as $maxlen |
-				$data | to_entries[] |
-				"##    \(.key):\(" " * ($maxlen - (.key | length) + 7))\(.value)"
-			' /opt/ffmpeg/versions.json)"
-	logger "##"
-	if (( ${dst_duration%.*} >= 208 && ${dst_duration%.*} <= 212 )); then
-		logger "## duration=${dst_duration%.*} Complete jlse is running normally." green
-	else
-		logger "## duration=${dst_duration%.*}" red
-		logger "## The jlse cut range is higher or lower than expected (normal value is between 208-212 seconds)." red
-		exit 1
-	fi
-	logger "##     Complete test_jlse." green
-	logger "##     logfile: ${LOG_FILE}" green
+
+set +x
+logger "## ============================================================================="
+logger "## Report test_jlse."
+logger "## - versions:"
+logger "$(jq -r '
+		{
+			"ffmpeg-jlstsl",
+			"libavisynth",
+			"liblsmash-url",
+			"liblsmash",
+			"liblsmashsource-url",
+			"liblsmashsource",
+			"libobuparse"
+		} as $data | ($data | keys | map(length) | max) as $maxlen |
+			$data | to_entries[] |
+			"##    \(.key):\(" " * ($maxlen - (.key | length) + 7))\(.value)"
+		' /opt/ffmpeg/versions.json)"
+logger "##"
+set -x
+
+set +x
+if ! jlse --input "${INPUT}"; then
+	logger "## jlse failed with exit code $?. Stopping execution." red
+	exit 1
 fi
+set +x
+
+src_duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "${INPUT}")
+dst_duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "/join_logo_scp_trial/result/$(basename ${INPUT} .ts)/in_cutcm_logo.avs")
+logger "## - source:       ${INPUT}"
+logger "##    - duration:  ${src_duration%.*}"
+logger "## - destnation:   ${INPUT%.ts}.mp4"
+logger "##    - duration:  ${dst_duration%.*}"
+logger "##"
+if (( ${dst_duration%.*} >= 1435 && ${dst_duration%.*} <= 1445 )); then
+	logger "## duration=${dst_duration%.*} Complete jlse is running normally." green
+else
+	logger "## duration=${dst_duration%.*}" red
+	logger "## The jlse cut range is higher or lower than expected (normal value is between 208-212 seconds)." red
+	exit 1
+fi
+logger "##     Complete test_jlse." green
+logger "##     logfile: ${LOG_FILE}" green
